name: remote_database_setting
description: "A new Flutter project."
version: 1.0.0
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1
  # odoo_rpc: ^0.5.4
  odoo_rpc: ^0.5.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  pos_shared_preferences:
    git:
      url: https://github.com/YousenTech-Flutter/yousentech_pos_shared_preferences.git
      ref: master
  shared_widgets:
    git:
      url: https://github.com/YousenTech-Flutter/yousentech_pos_shared_widgets.git
      ref: master
  yousentech_pos_token:
    git:
      url: https://github.com/YousenTech-Flutter/yousentech_pos_token.git
      ref: master
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
dependency_overrides:
  network_info_plus: ^4.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/image/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Tajawal
  #     fonts:
  #       - asset: assets/fonts/Tajawal-Medium.ttf
  #   - family: Tajawal
  #     fonts:
  #       - asset: assets/fonts/Tajawal-Bold.ttf
  #   - family: ARIALBD
  #     fonts:
  #       - asset: assets/fonts/ARIALBD.TTF
  #   - family: ARIALBD
  #     fonts:
  #       - asset: assets/fonts/ARIAL.TTF
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
